name: Renovate

on:
  workflow_dispatch:
  schedule:
    - cron: '00 1 * * 1'  # At 01:00 on Mondays.

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v36.0.0
        with:
          renovate-version: 35.0.0
          token: ${{ secrets.RENOVATE_TOKEN }}
